#!/bin/bash
# tweak .usr (actually, .f ) file
if echo $PPS | grep -q 'CVODE' ; then
   CVODE=1
else
   CVODE=0
fi

if echo $PPS | grep -q 'CMT' ; then
   CMT=1
else
   CMT=0
fi
if echo $PPS | grep -q 'CMTPART' ; then
   CMTPRT=1
else
   CMTPRT=0
fi

rm -f $CASENAME.f
cp -pv $CASENAME.usr $CASENAME.f

if ! cat $CASENAME.f | grep -qi "subroutine.*usrsetvert" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine usrsetvert(glo_num,nel,nx,ny,nz) ! to modify glo_num
      integer*8 glo_num(1)

      return
      end
_ACEOF
fi

if ! cat $CASENAME.f | grep -qi "subroutine.*userqtl" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine userqtl

      call userqtl_scig

      return
      end
_ACEOF
fi


if [ $CVODE -ne 0 ]; then

if ! cat $CASENAME.f | grep -qi "^#include.*cvode_aux.*\.h" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
#include "cvode_aux.h"
_ACEOF
fi

if ! cat $CASENAME.f | grep -qi "^#include.*cvode_jtimes.*\.h" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
#include "cvode_jtimes.h"
_ACEOF
fi

if ! cat $CASENAME.f | grep -qi "^#include.*cvode_preco.*\.h" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
#include "cvode_preco_dummy.h"
_ACEOF
fi

fi

if [ $CMT -ne 0 ]; then
if ! cat $CASENAME.f | grep -qi "subroutine.*cmt_usrflt" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine cmt_usrflt(rmult) ! user defined filter
      include 'SIZE'
      real rmult(lx1)
      call rone(rmult,lx1)
      return
      end
_ACEOF
fi

if ! cat $CASENAME.f | grep -qi "subroutine.*cmt_userflux" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine cmt_userflux ! user defined flux
      include 'SIZE'
      include 'TOTAL'
      include 'NEKUSE'
      include 'CMTDATA'
      real fluxout(lx1*lz1)
      return
      end
_ACEOF
fi

if ! cat $CASENAME.f | grep -qi "subroutine.*cmt_userEOS" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine cmt_userEOS ! user defined EOS 
      include 'SIZE'
      include 'TOTAL'
      include 'NEKUSE'
      include 'CMTDATA'

      return
      end
_ACEOF
fi
fi

if [ $CMTPRT -ne 0 ]; then
if ! cat $CASENAME.f | grep -qi "subroutine.*place_particles_user" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine place_particles_user 
      include 'SIZE'
      include 'TOTAL'
      include 'CMTDATA'
      include 'CMTPART'
      real unif_random,unif_random_norm
      external unif_random,unif_random_norm
c     USER SET BOUNDS TO DISTRIBUTION PARTICLES IN
      rxbo(1,1) = xdrange(1,1) + rspl**(1./3.)*dp(2)     ! X-Left
      rxbo(2,1) = xdrange(2,1) - rspl**(1./3.)*dp(2)     ! X-Right
      rxbo(1,2) = xdrange(1,2) + rspl**(1./3.)*dp(2)     ! Y-Left
      rxbo(2,2) = xdrange(2,2) - rspl**(1./3.)*dp(2)     ! Y-Right
      rxbo(1,3) = xdrange(1,3) + rspl**(1./3.)*dp(2)     ! Z-Left
      rxbo(2,3) = xdrange(2,3) - rspl**(1./3.)*dp(2)     ! Z-Right
      if (ipart_restartr .eq. 0) then
c        USER PLACE X,Y,Z PARTICLES COORDS IF DISTRIBUTING PARTICLES
         x_part(0) = unif_random(rxbo(1,1),rxbo(2,1)) ! X-COORD
         x_part(1) = unif_random(rxbo(1,2),rxbo(2,2)) ! Y-COORD
         x_part(2) = unif_random(rxbo(1,3),rxbo(2,3)) ! Z-COORD
c        USER SET PARTICLE DIAMETERS IF DISTRIBUTING PARTICLES
         d_part    = unif_random(dp(1),dp(2))              ! UR
c        d_part    = unif_random_norm(dp(1),dp(2),STD_DEV) ! URN
      endif
      return
      end
_ACEOF
fi
if ! cat $CASENAME.f | grep -qi "subroutine.*usr_particles_f_user" ; then
cat >> $CASENAME.f << _ACEOF

c automatically added by makenek
      subroutine usr_particles_f_user(i) 
      include 'SIZE'
      include 'TOTAL'
      include 'CMTDATA'
      include 'CMTPART'
      parameter(rgrav = 9.8)
c     USER SET BODY FORCES 
      f_part(0) = 0.0
c     f_part(1) = -rgrav*rpart(jvol,i)*(rpart(jrhop,i)-rpart(jrho,i))
      f_part(1) = 0.0
      f_part(2) = 0.0
      return
      end
_ACEOF
fi
fi
